version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: large
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update --fix-missing -y
            sudo apt-get install -y \
              git curl zip unzip wget bc bison flex build-essential \
              libssl-dev ccache zstd aria2 python3

      - run:
          name: Drivers KSU
          command: curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main

      - run:
          name: Permission build.sh
          command: chmod +x build.sh

      - run:
          name: Run build script
          command: ./build.sh

workflows:
  version: 2
  kernel-ci:
    jobs:
      - build