name: Build KSU

on:
  push:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup timezone
        uses: szenius/set-timezone@master
        with:
          timezoneLinux: "America/Sao_Paulo"

      - name: Run build script
        run: |
          export KBUILD_BUILD_USER=nobody
          export KBUILD_BUILD_HOST=android-build
          source build.sh --su
          echo "ZIPNAME=${ZIPNAME}" >> $GITHUB_ENV

      - name: Upload build artifact
        uses: actions/upload-artifact@main
        with:
          path: ${{ env.ZIPNAME }}

      - name: Upload to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          document: ${{ env.ZIPNAME }}
